

package community.flock.kmapper;

import com.intellij.testFramework.TestDataPath;
import kctf.ClasspathBasedStandardLibrariesPathProvider;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.jetbrains.kotlin.test.services.KotlinStandardLibrariesPathProvider;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/**
 * This class is generated by {@link kctf.MainKt}. DO NOT MODIFY MANUALLY
 */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/src/test/data")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
    @Test
    public void testAllFilesPresentInData() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(
            this.getClass(),
            new File("compiler-plugin/src/test/data"),
            Pattern.compile("^(.+)\\.kt$"),
            null,
            TargetBackend.JVM_IR,
            true
        );
    }

    @Test
    @TestMetadata("simple.kt")
    public void testSimple() {
        runTest("compiler-plugin/src/test/data/simple.kt");
    }

    @Override
    public KotlinStandardLibrariesPathProvider createKotlinStandardLibrariesPathProvider() {
        return ClasspathBasedStandardLibrariesPathProvider.INSTANCE;
    }
}
